import type { Invoice, Expense, FinancialSummary } from '@/features/billing/types';

export const DEMO_FINANCIAL_SUMMARY: FinancialSummary = {
  totalRevenue: 482450,
  totalPaid: 446200,
  totalPending: 36250,
  totalExpenses: 138900,
  netMargin: 307300,
  marginPercentage: 63.7,
  invoicesCount: 382,
  expensesCount: 28,
  realizedPercentage: 92.5,
  collectionsByMethod: {
    UPI: 248500,
    CASH: 112400,
    CARD: 54300,
    NET_BANKING: 31000,
  },
  expensesByCategory: {
    REAGENTS: 68500,
    CONSUMABLES: 18400,
    MAINTENANCE: 18000,
    UTILITIES: 17250,
    OTHER: 16750,
  },
};

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 'inv-01',
    invoiceNumber: 'INV-2024-8842',
    patientId: 'patient-02',
    patientName: 'Sunita Rao',
    patientMrn: 'PT-10488',
    patientPhone: '+91 98450 91823',
    reportId: 'demo-01',
    testsBilled: 'Urine Routine + Microscopic',
    subtotal: 350,
    discount: 0,
    totalAmount: 350,
    paidAmount: 350,
    paymentStatus: 'PAID',
    paymentMethod: 'UPI',
    paidAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-101',
        description: 'Urine Routine & Microscopic Examination',
        unitPrice: 350,
        quantity: 1,
        total: 350,
      },
    ],
  },
  {
    id: 'inv-02',
    invoiceNumber: 'INV-2024-8841',
    patientId: 'patient-01',
    patientName: 'Ramesh V. Gupta',
    patientMrn: 'PT-10492',
    patientPhone: '+91 98201 23456',
    reportId: 'demo-02',
    testsBilled: 'HbA1c + Lipid Profile + FBS',
    subtotal: 1850,
    discount: 200,
    totalAmount: 1650,
    paidAmount: 1650,
    paymentStatus: 'PAID',
    paymentMethod: 'CASH',
    paidAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-201',
        description: 'Glycated Hemoglobin (HbA1c)',
        unitPrice: 650,
        quantity: 1,
        total: 650,
      },
      {
        id: 'item-202',
        description: 'Lipid Profile Comprehensive',
        unitPrice: 950,
        quantity: 1,
        total: 950,
      },
      {
        id: 'item-203',
        description: 'Fasting Blood Sugar (FBS)',
        unitPrice: 250,
        quantity: 1,
        total: 250,
      },
    ],
  },
  {
    id: 'inv-03',
    invoiceNumber: 'INV-2024-8840',
    patientId: 'patient-05',
    patientName: 'Meenakshi Sundaram',
    patientMrn: 'PT-10214',
    patientPhone: '+91 94440 55123',
    reportId: 'demo-05',
    testsBilled: 'Electrolytes + Troponin I',
    subtotal: 1900,
    discount: 0,
    totalAmount: 1900,
    paidAmount: 0,
    paymentStatus: 'UNPAID',
    paymentMethod: 'OTHER',
    paidAt: null,
    notes: 'Corporate Account: Apollo Health Shield',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-301',
        description: 'Serum Electrolytes (Na+, K+, Cl-)',
        unitPrice: 700,
        quantity: 1,
        total: 700,
      },
      {
        id: 'item-302',
        description: 'High-Sensitivity Troponin I',
        unitPrice: 1200,
        quantity: 1,
        total: 1200,
      },
    ],
  },
  {
    id: 'inv-04',
    invoiceNumber: 'INV-2024-8839',
    patientId: 'patient-04',
    patientName: 'Farhan A. Mansoori',
    patientMrn: 'PT-10390',
    patientPhone: '+91 91670 44921',
    reportId: 'demo-04',
    testsBilled: 'Serum Creatinine + KFT',
    subtotal: 950,
    discount: 0,
    totalAmount: 950,
    paidAmount: 950,
    paymentStatus: 'PAID',
    paymentMethod: 'UPI',
    paidAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-401',
        description: 'Kidney Function Test (KFT) with Electrolytes',
        unitPrice: 950,
        quantity: 1,
        total: 950,
      },
    ],
  },
  {
    id: 'inv-05',
    invoiceNumber: 'INV-2024-8838',
    patientId: 'patient-03',
    patientName: 'Ananya Priyadarshini',
    patientMrn: 'PT-10115',
    patientPhone: '+91 99370 77412',
    reportId: 'demo-03',
    testsBilled: 'Complete Blood Count (CBC) + ESR',
    subtotal: 480,
    discount: 0,
    totalAmount: 480,
    paidAmount: 480,
    paymentStatus: 'PAID',
    paymentMethod: 'CARD',
    paidAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-501',
        description: 'Complete Hemogram / CBC with Automated Differential',
        unitPrice: 380,
        quantity: 1,
        total: 380,
      },
      {
        id: 'item-502',
        description: 'Erythrocyte Sedimentation Rate (ESR)',
        unitPrice: 100,
        quantity: 1,
        total: 100,
      },
    ],
  },
  {
    id: 'inv-06',
    invoiceNumber: 'INV-2024-8837',
    patientId: 'patient-06',
    patientName: 'Vikram S. Patil',
    patientMrn: 'PT-10289',
    patientPhone: '+91 98210 11928',
    reportId: null,
    testsBilled: 'Thyroid Profile Total (T3, T4, TSH)',
    subtotal: 750,
    discount: 50,
    totalAmount: 700,
    paidAmount: 700,
    paymentStatus: 'PAID',
    paymentMethod: 'UPI',
    paidAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-601',
        description: 'Thyroid Profile (Total T3, Total T4, Ultrasensitive TSH)',
        unitPrice: 750,
        quantity: 1,
        total: 750,
      },
    ],
  },
  {
    id: 'inv-07',
    invoiceNumber: 'INV-2024-8836',
    patientId: 'patient-07',
    patientName: 'Suman Sharma',
    patientMrn: 'PT-10312',
    patientPhone: '+91 97112 33499',
    reportId: null,
    testsBilled: 'Liver Function Test (LFT) + Bilirubin',
    subtotal: 850,
    discount: 0,
    totalAmount: 850,
    paidAmount: 850,
    paymentStatus: 'PAID',
    paymentMethod: 'CASH',
    paidAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'item-701',
        description: 'Liver Function Profile Complete',
        unitPrice: 850,
        quantity: 1,
        total: 850,
      },
    ],
  },
];

export const DEMO_EXPENSES: Expense[] = [
  {
    id: 'exp-01',
    expenseNumber: 'EXP-412',
    title: 'Roche Cobas c501 Reagent Cassette (Creatinine/Lipid)',
    amount: 28500,
    category: 'REAGENTS',
    categoryLabel: 'Reagents & Kits',
    expenseDate: '2024-10-24',
    paymentMethod: 'NET_BANKING',
    vendor: 'Transasia Bio-Medicals',
    vendorInvoiceNumber: 'TX-9041',
    notes: 'Direct reagent replenishment for clinical chemistry bench',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp-02',
    expenseNumber: 'EXP-411',
    title: 'SRL Diagnostics Outsourced Batch Settlement (Batch #88)',
    amount: 14200,
    category: 'OTHER',
    categoryLabel: 'Reference Lab',
    expenseDate: '2024-10-23',
    paymentMethod: 'NET_BANKING',
    vendor: 'SRL Limited',
    vendorInvoiceNumber: 'SRL-INV-1092',
    notes: 'Karyotyping, HLA-B27, and Serum Protein Electrophoresis',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp-03',
    expenseNumber: 'EXP-410',
    title: 'Vacutainer EDTA & SST Tubes (Box of 500) + Needles',
    amount: 6400,
    category: 'CONSUMABLES',
    categoryLabel: 'Consumables',
    expenseDate: '2024-10-22',
    paymentMethod: 'UPI',
    vendor: 'BD India Healthcare',
    vendorInvoiceNumber: 'BD-8819',
    notes: 'Phlebotomy supplies replenishment',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp-04',
    expenseNumber: 'EXP-409',
    title: 'Clinical Bio-Medical Waste Disposal (October)',
    amount: 4800,
    category: 'UTILITIES',
    categoryLabel: 'Utilities',
    expenseDate: '2024-10-20',
    paymentMethod: 'OTHER',
    vendor: 'Maridi Waste Management',
    vendorInvoiceNumber: 'MW-4401',
    notes: 'NABL compliant bio-medical incineration and barcode tracking',
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp-05',
    expenseNumber: 'EXP-408',
    title: 'Phlebotomy runner fuel allowances (5 field agents)',
    amount: 3250,
    category: 'OTHER',
    categoryLabel: 'Phlebotomy Travel',
    expenseDate: '2024-10-18',
    paymentMethod: 'CASH',
    vendor: 'Staff Reimbursement',
    vendorInvoiceNumber: 'VOUCH-188',
    notes: 'Home sample collection travel reimbursement',
    createdAt: new Date(Date.now() - 144 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp-06',
    expenseNumber: 'EXP-407',
    title: 'Sysmex XN-350 6-Month Preventative Maintenance AMC',
    amount: 18000,
    category: 'MAINTENANCE',
    categoryLabel: 'Machine AMC',
    expenseDate: '2024-10-15',
    paymentMethod: 'NET_BANKING',
    vendor: 'Sysmex India Pvt Ltd',
    vendorInvoiceNumber: 'SYS-AMC-2024',
    notes: 'Hydraulic tubing replacement, optical sensor laser calibration',
    createdAt: new Date(Date.now() - 216 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'exp-07',
    expenseNumber: 'EXP-406',
    title: 'High-Load Autoclave & Centrifuge Electricity Bill',
    amount: 12450,
    category: 'UTILITIES',
    categoryLabel: 'Utilities',
    expenseDate: '2024-10-10',
    paymentMethod: 'UPI',
    vendor: 'Adani Electricity Mumbai',
    vendorInvoiceNumber: 'AD-ELEC-9021',
    notes: 'Monthly laboratory facility electrical consumption',
    createdAt: new Date(Date.now() - 360 * 60 * 60 * 1000).toISOString(),
  },
];
