import type { CollectionRequest, Phlebotomist } from '@/features/collections/types';

export const DEMO_PHLEBOTOMISTS: Phlebotomist[] = [
  {
    id: 'phleb-01',
    name: 'Ravi Kumar',
    phone: '+91 98451 90812',
    currentZone: 'Indiranagar / Domlur',
    vehicleNumber: 'KA-04-EK-9821',
    activeAssignmentsCount: 2,
    status: 'ON_DUTY',
    coldBoxId: 'COLD-BOX-04',
    coldBoxTemp: '4.2°C',
    lastPing: '2m ago',
  },
  {
    id: 'phleb-02',
    name: 'Deepak Sharma',
    phone: '+91 98860 11442',
    currentZone: 'Koramangala / HSR',
    vehicleNumber: 'KA-01-ME-1142',
    activeAssignmentsCount: 1,
    status: 'ON_DUTY',
    coldBoxId: 'COLD-BOX-02',
    coldBoxTemp: '3.8°C',
    lastPing: '4m ago',
  },
  {
    id: 'phleb-03',
    name: 'Vikram Solanki',
    phone: '+91 97410 44521',
    currentZone: 'Whitefield / Mahadevapura',
    vehicleNumber: 'KA-03-JJ-5561',
    activeAssignmentsCount: 2,
    status: 'ON_DUTY',
    coldBoxId: 'COLD-BOX-07',
    coldBoxTemp: '4.6°C',
    lastPing: '1m ago',
  },
  {
    id: 'phleb-04',
    name: 'Rajesh Gowda',
    phone: '+91 99002 33118',
    currentZone: 'Jayanagar / JP Nagar',
    vehicleNumber: 'KA-05-AA-7744',
    activeAssignmentsCount: 0,
    status: 'AVAILABLE',
    coldBoxId: 'COLD-BOX-01',
    coldBoxTemp: '4.0°C',
    lastPing: 'just now',
  },
];

export const DEMO_COLLECTIONS: CollectionRequest[] = [
  {
    id: 'col-req-01',
    labId: 'lab-apex-01',
    requestNumber: 'COL-2026-081',
    patientId: 'pt-10492',
    patientName: 'Anand K. Verma',
    patientPhone: '+91 98101 23456',
    patientAge: '54',
    patientSex: 'MALE',
    address: 'Flat 402, Shanti Nilayam, 12th Main, Indiranagar 2nd Stage',
    locality: 'Indiranagar',
    preferredDate: '2026-09-11',
    timeSlot: '07:30 - 08:30 AM',
    status: 'IN_TRANSIT',
    assignedPhlebotomistId: 'phleb-01',
    assignedPhlebotomistName: 'Ravi Kumar',
    isFastingRequired: true,
    testNames: ['Lipid Profile Extended', 'HbA1c & Fasting Blood Sugar'],
    specialInstructions: 'Ring doorbell twice. Patient is a senior citizen on 2nd floor.',
    samples: [
      {
        id: 'samp-01',
        collectionRequestId: 'col-req-01',
        tubeType: 'FLUORIDE',
        barcode: 'BD-FL-8821',
        notes: 'Fasting Plasma Glucose',
        createdAt: '2026-09-11T07:42:00Z',
      },
      {
        id: 'samp-02',
        collectionRequestId: 'col-req-01',
        tubeType: 'EDTA',
        barcode: 'BD-EDTA-8822',
        notes: 'Whole Blood HbA1c',
        createdAt: '2026-09-11T07:43:00Z',
      },
      {
        id: 'samp-03',
        collectionRequestId: 'col-req-01',
        tubeType: 'SERUM',
        barcode: 'BD-SST-8823',
        notes: 'Serum for Lipid Profile',
        createdAt: '2026-09-11T07:44:00Z',
      },
    ],
    collectedAt: '2026-09-11T07:45:00Z',
    deliveredToLabAt: null,
    reportId: null,
    createdAt: '2026-09-11T06:15:00Z',
    updatedAt: '2026-09-11T07:45:00Z',
  },
  {
    id: 'col-req-02',
    labId: 'lab-apex-01',
    requestNumber: 'COL-2026-082',
    patientId: 'pt-10488',
    patientName: 'Sunita Mehra',
    patientPhone: '+91 98450 67123',
    patientAge: '62',
    patientSex: 'FEMALE',
    address: 'House #48, 4th Cross, Koramangala 4th Block, Near BDA Complex',
    locality: 'Koramangala',
    preferredDate: '2026-09-11',
    timeSlot: '08:00 - 09:00 AM',
    status: 'SAMPLE_COLLECTED',
    assignedPhlebotomistId: 'phleb-02',
    assignedPhlebotomistName: 'Deepak Sharma',
    isFastingRequired: true,
    testNames: ['Comprehensive Metabolic Profile (KFT/LFT)', 'Thyroid Profile (TSH/T3/T4)'],
    specialInstructions: 'Hard veins. Use 23G butterfly needle if necessary.',
    samples: [
      {
        id: 'samp-04',
        collectionRequestId: 'col-req-02',
        tubeType: 'SERUM',
        barcode: 'BD-SST-8824',
        notes: 'Serum Separator Tube',
        createdAt: '2026-09-11T08:15:00Z',
      },
      {
        id: 'samp-05',
        collectionRequestId: 'col-req-02',
        tubeType: 'HEPARIN',
        barcode: 'BD-HEP-8825',
        notes: 'Heparinized Plasma',
        createdAt: '2026-09-11T08:16:00Z',
      },
    ],
    collectedAt: '2026-09-11T08:18:00Z',
    deliveredToLabAt: null,
    reportId: null,
    createdAt: '2026-09-11T06:30:00Z',
    updatedAt: '2026-09-11T08:18:00Z',
  },
  {
    id: 'col-req-03',
    labId: 'lab-apex-01',
    requestNumber: 'COL-2026-083',
    patientId: 'pt-10492',
    patientName: 'Ramesh V. Gupta',
    patientPhone: '+91 98765 43210',
    patientAge: '58',
    patientSex: 'MALE',
    address: 'Plot 15, Near Water Tank, Model Town / Indiranagar',
    locality: 'Indiranagar',
    preferredDate: '2026-09-11',
    timeSlot: '07:00 - 08:00 AM',
    status: 'DELIVERED_TO_LAB',
    assignedPhlebotomistId: 'phleb-01',
    assignedPhlebotomistName: 'Ravi Kumar',
    isFastingRequired: true,
    testNames: ['HbA1c & Fasting Plasma Glucose'],
    specialInstructions: 'Patient requested WhatsApp copy of receipt upon draw.',
    samples: [
      {
        id: 'samp-06',
        collectionRequestId: 'col-req-03',
        tubeType: 'FLUORIDE',
        barcode: 'BD-FL-8826',
        notes: 'Fluoride EDTA',
        createdAt: '2026-09-11T07:15:00Z',
      },
      {
        id: 'samp-07',
        collectionRequestId: 'col-req-03',
        tubeType: 'EDTA',
        barcode: 'BD-EDTA-8827',
        notes: 'Whole Blood',
        createdAt: '2026-09-11T07:16:00Z',
      },
    ],
    collectedAt: '2026-09-11T07:20:00Z',
    deliveredToLabAt: '2026-09-11T08:45:00Z',
    reportId: 'demo-02',
    createdAt: '2026-09-10T20:00:00Z',
    updatedAt: '2026-09-11T08:45:00Z',
  },
  {
    id: 'col-req-04',
    labId: 'lab-apex-01',
    requestNumber: 'COL-2026-084',
    patientId: 'pt-10480',
    patientName: 'Ananya Priyadarshini',
    patientPhone: '+91 88201 56341',
    patientAge: '29',
    patientSex: 'FEMALE',
    address: 'Tower 3, Apt 1104, Prestige Tech Park Road, Whitefield',
    locality: 'Whitefield',
    preferredDate: '2026-09-11',
    timeSlot: '09:30 - 10:30 AM',
    status: 'ASSIGNED',
    assignedPhlebotomistId: 'phleb-03',
    assignedPhlebotomistName: 'Vikram Solanki',
    isFastingRequired: false,
    testNames: ['Complete Blood Count (CBC) with ESR', 'Vitamin D3 (25-OH) Total'],
    specialInstructions: 'Security gate access code is 4491.',
    samples: [],
    collectedAt: null,
    deliveredToLabAt: null,
    reportId: null,
    createdAt: '2026-09-11T07:10:00Z',
    updatedAt: '2026-09-11T07:50:00Z',
  },
  {
    id: 'col-req-05',
    labId: 'lab-apex-01',
    requestNumber: 'COL-2026-085',
    patientId: 'pt-10472',
    patientName: 'Farhan A. Mansoori',
    patientPhone: '+91 97110 88204',
    patientAge: '44',
    patientSex: 'MALE',
    address: 'House 88, 8th Main Road, Jayanagar 4th Block',
    locality: 'Jayanagar',
    preferredDate: '2026-09-11',
    timeSlot: '09:00 - 10:00 AM',
    status: 'REQUESTED',
    assignedPhlebotomistId: null,
    assignedPhlebotomistName: null,
    isFastingRequired: false,
    testNames: ['Serum Creatinine & Electrolytes', 'Urine Routine & Microscopy'],
    specialInstructions: 'Provide sterile urine container on arrival.',
    samples: [],
    collectedAt: null,
    deliveredToLabAt: null,
    reportId: null,
    createdAt: '2026-09-11T07:25:00Z',
    updatedAt: '2026-09-11T07:25:00Z',
  },
  {
    id: 'col-req-06',
    labId: 'lab-apex-01',
    requestNumber: 'COL-2026-086',
    patientId: 'pt-10461',
    patientName: 'Meenakshi Sundaram',
    patientPhone: '+91 94441 90281',
    patientAge: '63',
    patientSex: 'FEMALE',
    address: 'Villa 12, Green Glen Layout, 14th Cross, HSR Layout Sector 3',
    locality: 'HSR Layout',
    preferredDate: '2026-09-11',
    timeSlot: '10:30 - 11:30 AM',
    status: 'REQUESTED',
    assignedPhlebotomistId: null,
    assignedPhlebotomistName: null,
    isFastingRequired: false,
    testNames: ['High Sensitivity Troponin-I (hs-cTnI)', 'CK-MB Quantitative'],
    specialInstructions: 'Urgent cardiac evaluation. Expedited accession required.',
    samples: [],
    collectedAt: null,
    deliveredToLabAt: null,
    reportId: null,
    createdAt: '2026-09-11T08:00:00Z',
    updatedAt: '2026-09-11T08:00:00Z',
  },
  {
    id: 'col-req-07',
    labId: 'lab-apex-01',
    requestNumber: 'COL-2026-087',
    patientId: 'pt-10289',
    patientName: 'Vikram S. Patil',
    patientPhone: '+91 98204 77112',
    patientAge: '51',
    patientSex: 'MALE',
    address: 'Bungalow 7, Palm Meadows, Ramagondanahalli, Whitefield',
    locality: 'Whitefield',
    preferredDate: '2026-09-11',
    timeSlot: '11:00 - 12:00 PM',
    status: 'ASSIGNED',
    assignedPhlebotomistId: 'phleb-03',
    assignedPhlebotomistName: 'Vikram Solanki',
    isFastingRequired: false,
    testNames: ['Widal Slide Agglutination', 'Dengue NS1 Antigen Rapid'],
    specialInstructions: 'Fever since 3 days. Wear gloves and mask.',
    samples: [],
    collectedAt: null,
    deliveredToLabAt: null,
    reportId: null,
    createdAt: '2026-09-11T08:20:00Z',
    updatedAt: '2026-09-11T08:40:00Z',
  },
];
