import type { ReferringDoctor, CommissionLedgerEntry, LabCommissionSummary } from '@/features/referrals/types';

export const DEMO_DOCTORS: ReferringDoctor[] = [
  {
    id: 'doc-01',
    name: 'Dr. Sunil K. Chawla',
    specialty: 'Endocrinologist',
    registrationNumber: 'KMC-48192',
    clinic: 'Apex Diabetes Care, Bandra West, Mumbai',
    phone: '+91 98201 44821',
    email: 'dr.chawla@apexdiabetes.org',
    commissionType: 'PERCENTAGE',
    commissionValue: 15,
    activeCasesCount: 38,
    pendingAmount: 14200,
    settledAmount: 28500,
    bankAccount: '•••• •••• •••• 4920',
    ifsc: 'HDFC0001042',
    pan: 'AAAPC2019K',
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'doc-02',
    name: 'Dr. Priya Deshmukh',
    specialty: 'Internal Medicine',
    registrationNumber: 'MMC-33290',
    clinic: 'Lilavati OPD Clinic, Bandra, Mumbai',
    phone: '+91 98450 11920',
    email: 'dr.priya@lilavatiopd.com',
    commissionType: 'FLAT',
    commissionValue: 200,
    activeCasesCount: 24,
    pendingAmount: 4800,
    settledAmount: 16000,
    bankAccount: '•••• •••• •••• 8102',
    ifsc: 'ICIC0000108',
    pan: 'BKAPD9201J',
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'doc-03',
    name: 'Dr. Rajesh Kaul',
    specialty: 'General Physician',
    registrationNumber: 'DMC-89102',
    clinic: 'City Polyclinic, Andheri East, Mumbai',
    phone: '+91 97110 33812',
    email: 'dr.kaul@citypolyclinic.in',
    commissionType: 'PERCENTAGE',
    commissionValue: 10,
    activeCasesCount: 52,
    pendingAmount: 0,
    settledAmount: 34200,
    bankAccount: '•••• •••• •••• 3319',
    ifsc: 'SBIN0004921',
    pan: 'CKRPK1102L',
    createdAt: new Date(Date.now() - 240 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'doc-04',
    name: 'Dr. Anjali Mehta',
    specialty: 'Nephrology',
    registrationNumber: 'GAC-19283',
    clinic: 'Apex Kidney Institute, Mulund West, Mumbai',
    phone: '+91 94441 88201',
    email: 'dr.mehta@apexkidney.org',
    commissionType: 'PERCENTAGE',
    commissionValue: 12,
    activeCasesCount: 19,
    pendingAmount: 8450,
    settledAmount: 21900,
    bankAccount: '•••• •••• •••• 5541',
    ifsc: 'UTIB0000842',
    pan: 'DAMPM4490Q',
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'doc-05',
    name: 'Dr. Vikramaditya Rathore',
    specialty: 'Cardiology',
    registrationNumber: 'RMC-54219',
    clinic: 'Apollo Spectra, Tardeo, Mumbai',
    phone: '+91 99880 12345',
    email: 'dr.rathore@apollospectra.com',
    commissionType: 'NONE',
    commissionValue: 0,
    activeCasesCount: 41,
    pendingAmount: 0,
    settledAmount: 0,
    bankAccount: '•••• •••• •••• 1920',
    ifsc: 'KKBK0001104',
    pan: 'EAKPR8821Z',
    createdAt: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_COMMISSION_SUMMARY: LabCommissionSummary = {
  totalPending: 142800,
  totalSettled: 385500,
  doctorCount: 48,
  totalReferralsMTD: 312,
  disbursedMTD: 385500,
};

export const DEMO_LEDGER_ENTRIES: Record<string, CommissionLedgerEntry[]> = {
  'doc-01': [
    {
      id: 'led-100',
      doctorId: 'doc-01',
      reportId: 'demo-accrual',
      amount: 13570,
      status: 'PENDING',
      settledAt: null,
      notes: '15% on Monthly Outpatient Diagnostic Batteries (24 Referrals)',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      patientName: 'Batched Clinical Referrals (24 Patients)',
      panelName: 'Executive Full Body Health Battery',
      billAmount: 90466.67,
    },
    {
      id: 'led-101',
      doctorId: 'doc-01',
      reportId: 'demo-02',
      amount: 277.5,
      status: 'PENDING',
      settledAt: null,
      notes: '15% on HbA1c & Fasting Glucose',
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      patientName: 'Ramesh V. Gupta',
      panelName: 'HbA1c + Lipid Profile',
      billAmount: 1850,
    },
    {
      id: 'led-102',
      doctorId: 'doc-01',
      reportId: 'demo-04',
      amount: 240,
      status: 'PENDING',
      settledAt: null,
      notes: '15% on KFT Profile',
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      patientName: 'Farhan A. Mansoori',
      panelName: 'KFT + Serum Electrolytes',
      billAmount: 1600,
    },
    {
      id: 'led-103',
      doctorId: 'doc-01',
      reportId: 'demo-10',
      amount: 112.5,
      status: 'PENDING',
      settledAt: null,
      notes: '15% on Thyroid Profile',
      createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
      patientName: 'Kavita Deshmukh',
      panelName: 'Thyroid Profile Total',
      billAmount: 750,
    },
    {
      id: 'led-104',
      doctorId: 'doc-01',
      reportId: 'demo',
      amount: 360,
      status: 'SETTLED',
      settledAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      notes: 'Settled NEFT #VCH-9410',
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      patientName: 'Sunita Rao',
      panelName: 'Comprehensive Executive Panel',
      billAmount: 2400,
    },
    {
      id: 'led-105',
      doctorId: 'doc-01',
      reportId: 'demo-05',
      amount: 37.5,
      status: 'SETTLED',
      settledAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      notes: 'Settled NEFT #VCH-9382',
      createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      patientName: 'Anita Desai',
      panelName: 'Fasting Plasma Glucose',
      billAmount: 250,
    },
  ],
  'doc-02': [
    {
      id: 'led-201',
      doctorId: 'doc-02',
      amount: 200,
      status: 'PENDING',
      settledAt: null,
      notes: 'Flat referral fee per outpatient consult',
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      patientName: 'Meenakshi Sundaram',
      panelName: 'Lipid Profile & Uric Acid',
      billAmount: 1100,
    },
    {
      id: 'led-202',
      doctorId: 'doc-02',
      amount: 200,
      status: 'PENDING',
      settledAt: null,
      notes: 'Flat referral fee',
      createdAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
      patientName: 'Devendra Joshi',
      panelName: 'Liver Function Test (LFT)',
      billAmount: 850,
    },
    {
      id: 'led-203',
      doctorId: 'doc-02',
      amount: 4400,
      status: 'PENDING',
      settledAt: null,
      notes: '22 flat outpatient referrals @ ₹200/patient',
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      patientName: 'Lilavati OPD Batch Referrals (22 Cases)',
      panelName: 'Routine Diagnostic Workup',
      billAmount: 24500,
    },
    {
      id: 'led-204',
      doctorId: 'doc-02',
      amount: 4000,
      status: 'SETTLED',
      settledAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      notes: 'Settled IMPS #VCH-9204',
      createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      patientName: 'Lilavati OPD Batch #12',
      panelName: 'General Health Batteries',
      billAmount: 21000,
    },
  ],
};
