import type { OutsourcedTest, OutsourcedSummaryStats } from '@/features/referrals/types';

export const DEMO_OUTSOURCED_TESTS: OutsourcedTest[] = [
  {
    id: 'out-01',
    labId: 'lab-demo',
    reportId: 'demo-02',
    reportNumber: 'R-20260922-0001',
    patientName: 'Ramesh V. Gupta',
    patientAge: '52 Y',
    patientSex: 'MALE',
    testName: '25-OH Vitamin D Total (CLIA)',
    referenceLabName: 'Dr. Lal PathLabs (Sector 14 Hub)',
    status: 'SENT',
    cost: 400,
    patientFee: 1200,
    courierPartner: 'Blue Dart Express',
    courierTrackingNumber: 'BD-88492091',
    sentAt: '2026-09-22T14:30:00.000Z',
    notes: 'Serum tube centrifuged and packed with gel cool pack. Barcode: BD-88492091.',
    createdAt: '2026-09-22T11:00:00.000Z',
  },
  {
    id: 'out-02',
    labId: 'lab-demo',
    reportId: 'demo',
    reportNumber: 'R-20260922-0002',
    patientName: 'Sunita Rao',
    patientAge: '38 Y',
    patientSex: 'FEMALE',
    testName: 'Histopathology — Skin Punch Biopsy (H&E)',
    referenceLabName: 'SRL Diagnostics Central Reference Lab',
    status: 'PENDING',
    cost: 750,
    patientFee: 2000,
    courierPartner: 'Local Hub Runner (Deepak)',
    notes: 'Specimen fixed in 10% neutral buffered formalin. Awaiting 4 PM evening pickup.',
    createdAt: '2026-09-23T08:45:00.000Z',
  },
  {
    id: 'out-03',
    labId: 'lab-demo',
    reportId: 'demo-03',
    reportNumber: 'R-20260921-0003',
    patientName: 'Farhan A. Mansoori',
    patientAge: '45 Y',
    patientSex: 'MALE',
    testName: 'Thyroid Peroxidase Antibodies (Anti-TPO)',
    referenceLabName: 'Thyrocare Technologies Limited',
    status: 'RECEIVED',
    cost: 320,
    patientFee: 850,
    courierPartner: 'Delhivery Healthcare Logistics',
    courierTrackingNumber: 'DLV-99210411',
    sentAt: '2026-09-21T10:15:00.000Z',
    receivedAt: '2026-09-22T16:20:00.000Z',
    resultSummary: 'Anti-TPO: 14.2 IU/mL (Negative, Reference: < 34.0 IU/mL). Method: ECLIA.',
    notes: 'Final electronic PDF report verified and merged into master patient file.',
    createdAt: '2026-09-21T09:30:00.000Z',
  },
  {
    id: 'out-04',
    labId: 'lab-demo',
    reportId: 'demo-report-04',
    reportNumber: 'R-20260920-0004',
    patientName: 'Ananya Priyadarshini',
    patientAge: '29 Y',
    patientSex: 'FEMALE',
    testName: 'Urine Culture & Sensitivity (Aerobic)',
    referenceLabName: 'Metropolis Healthcare Referral Lab',
    status: 'RECEIVED',
    cost: 350,
    patientFee: 900,
    courierPartner: 'DTDC Express Health',
    courierTrackingNumber: 'DTDC-771920',
    sentAt: '2026-09-20T12:00:00.000Z',
    receivedAt: '2026-09-22T11:10:00.000Z',
    resultSummary: 'E. coli > 10^5 CFU/mL. Sensitive: Nitrofurantoin, Amikacin. Resistant: Ciprofloxacin.',
    notes: 'Pathologist Dr. Sunita Nair verified and appended antibiogram table to report.',
    createdAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'out-05',
    labId: 'lab-demo',
    reportId: 'demo-report-05',
    reportNumber: 'R-20260923-0005',
    patientName: 'Vikram S. Patil',
    patientAge: '61 Y',
    patientSex: 'MALE',
    testName: 'Serum Ferritin & Iron Saturation Profile',
    referenceLabName: 'Dr. Lal PathLabs (Sector 14 Hub)',
    status: 'SENT',
    cost: 450,
    patientFee: 1100,
    courierPartner: 'Blue Dart Express',
    courierTrackingNumber: 'BD-88493102',
    sentAt: '2026-09-23T09:15:00.000Z',
    notes: 'Sample dispatched with morning priority shipment. Expected result TAT: 24h.',
    createdAt: '2026-09-23T08:00:00.000Z',
  },
  {
    id: 'out-06',
    labId: 'lab-demo',
    reportId: 'demo-report-06',
    reportNumber: 'R-20260923-0006',
    patientName: 'Meenakshi Sundaram',
    patientAge: '56 Y',
    patientSex: 'FEMALE',
    testName: 'Hemoglobin Variant Analysis (HPLC / Thalassemia)',
    referenceLabName: 'Oncquest Laboratories Reference Unit',
    status: 'PENDING',
    cost: 600,
    patientFee: 1500,
    courierPartner: 'Special Courier Handover',
    notes: 'Whole blood EDTA tube chilled. Awaiting batch pickup with evening dispatch.',
    createdAt: '2026-09-23T09:30:00.000Z',
  },
];

export const DEMO_OUTSOURCED_SUMMARY: OutsourcedSummaryStats = {
  activeCount: 4, // 2 SENT + 2 PENDING
  pendingCount: 2,
  sentCount: 2,
  receivedMTD: 18,
  totalPayableB2B: 12450,
};

export const REFERENCE_LAB_OPTIONS = [
  'Dr. Lal PathLabs',
  'SRL Diagnostics',
  'Thyrocare Technologies',
  'Metropolis Healthcare',
  'Oncquest Laboratories',
  'Neuberg Diagnostics',
  'Apollo Diagnostics Reference Hub',
  'Other / Local Pathology Reference Lab',
];
